<?php
$page_title = 'Insights';
$page_description = 'Articles and thoughts from the Nexa Studio team.';
require __DIR__ . '/includes/header.php';
$posts = [
    ['tag' => 'Strategy', 'title' => 'The questions to ask before you redesign your website', 'date' => 'May 18, 2026', 'class' => 'post-art-blue'],
    ['tag' => 'Design', 'title' => 'A clearer way to think about your product’s first impression', 'date' => 'April 29, 2026', 'class' => 'post-art-peach'],
    ['tag' => 'Development', 'title' => 'Five small choices that make a site feel faster', 'date' => 'April 07, 2026', 'class' => 'post-art-green'],
];
?>
<section class="page-hero compact blog-hero"><div class="container page-hero-grid"><div><p class="eyebrow">Journal</p><h1>Ideas for building with a little more <em>intention.</em></h1><p class="lead">Notes on digital experiences, clearer decisions, and the details that make a business feel unmistakably itself.</p><p class="hero-microcopy"><i></i> Fresh thinking, when it is genuinely useful.</p></div><div class="blog-hero-visual" aria-hidden="true"><span>THE<br>GOOD<br>STUFF</span><i>•</i><b>2026</b></div></div></section>
<section class="journal-nav"><div class="container"><a class="active" href="blog.php">All articles</a><a href="blog.php#strategy">Strategy</a><a href="blog.php#design">Design</a><a href="blog.php#development">Development</a></div></section>
<section class="section featured-story-section"><div class="container featured-story"><div class="featured-story-art"><span>FIELD<br>NOTES</span><i></i><b></b><em>01</em></div><div class="featured-story-copy"><p class="post-meta">Featured story <i>•</i> May 26, 2026</p><h2>What a good website should do before it says a single word.</h2><p>A site starts working long before a visitor reads the headline. Here is how pacing, hierarchy, and visual confidence build trust in seconds.</p><a class="button" href="404.php">Read the story <span>→</span></a></div></div></section>
<section class="section blog-section"><div class="container blog-section-head"><div><p class="eyebrow">Latest notes</p><h2>Useful thinking for useful work.</h2></div><span>03 articles</span></div><div class="container blog-grid"><?php foreach ($posts as $post): ?><article class="post-card"><div class="post-art <?= escape($post['class']) ?>"><span>NS</span></div><div class="post-content"><p class="post-meta"><?= escape($post['tag']) ?> <i>•</i> <?= escape($post['date']) ?></p><h2><?= escape($post['title']) ?></h2><a href="404.php">Read article →</a></div></article><?php endforeach; ?></div></section>
<section class="journal-signup"><div class="container signup-panel"><div><p class="eyebrow">A quiet email, occasionally</p><h2>One thoughtful idea when it is worth sharing.</h2></div><form action="newsletter.php" method="post"><input type="hidden" name="csrf_token" value="<?= escape(csrf_token()) ?>"><label class="visually-hidden" for="journal-email">Email address</label><input id="journal-email" name="email" type="email" placeholder="Your email address" autocomplete="email" required><button class="button" type="submit">Keep me posted <span>→</span></button></form></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
