<?php
$page_title = 'Services';
$page_description = 'Brand strategy, web design, and development services from Nexa Studio.';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container narrow"><p class="eyebrow">Services</p><h1>Everything you need to make a <em>meaningful</em> first impression.</h1><p class="lead">Bring us in for one focused challenge or let us guide the whole journey from idea to launch.</p></div></section>
<section class="section service-list"><div class="container">
<article class="service-row"><span>01</span><div><h2>Brand strategy</h2><p>Clarify your place in the market and build a brand foundation your team can use every day.</p></div><ul><li>Research & workshops</li><li>Positioning</li><li>Messaging systems</li></ul></article>
<article class="service-row"><span>02</span><div><h2>Web design</h2><p>Shape a clear, expressive experience that guides people from first visit to real action.</p></div><ul><li>User journeys</li><li>UX/UI design</li><li>Design systems</li></ul></article>
<article class="service-row"><span>03</span><div><h2>Web development</h2><p>Turn strong ideas into well-crafted, responsive websites that are easy to manage and ready to grow.</p></div><ul><li>PHP development</li><li>Performance</li><li>Accessibility</li></ul></article>
</div></section>
<section class="section engagement-section"><div class="container section-heading split-heading"><div><p class="eyebrow">Ways to work together</p><h2>Choose the momentum your team needs.</h2></div><p class="section-note">Every engagement is shaped around the problem, not a pre-made package.</p></div><div class="container engagement-grid"><article class="engagement-card"><p class="engagement-label">01 / Focused</p><h3>Launch sprint</h3><p>For teams that need a sharp point of view and a fast, valuable next move.</p><ul><li>Strategy workshop</li><li>Direction & priorities</li><li>90-day roadmap</li></ul><a href="contact.php">Talk about a sprint →</a></article><article class="engagement-card featured-engagement"><p class="engagement-label">02 / End to end</p><h3>Digital foundation</h3><p>For businesses ready to connect their story, experience, and website in one considered launch.</p><ul><li>Brand & messaging</li><li>Website UX/UI</li><li>Responsive PHP build</li></ul><a href="contact.php">Plan your foundation →</a></article><article class="engagement-card"><p class="engagement-label">03 / Ongoing</p><h3>Product partner</h3><p>For teams with traction that need a steady creative and technical partner as they grow.</p><ul><li>Monthly design support</li><li>New landing pages</li><li>Iteration & optimisation</li></ul><a href="contact.php">Build a partnership →</a></article></div></section>
<section class="section service-faq-section"><div class="container faq-layout"><div><p class="eyebrow">Good to know</p><h2>Questions worth asking before we begin.</h2><p class="lead">The best projects start with a shared understanding of how we will work together.</p></div><div class="faq-list"><details open><summary>How long does a typical website project take?<span>+</span></summary><p>Most projects take 6–12 weeks, depending on the scope, content, and review cycles. We set clear milestones before starting.</p></details><details><summary>Can you work with our existing brand?<span>+</span></summary><p>Absolutely. We can build a website that gives an existing brand more clarity and consistency, or help evolve it when the time is right.</p></details><details><summary>Will our team be able to update the site?<span>+</span></summary><p>Yes. We build with handover in mind and can tailor the editing experience to the people maintaining it.</p></details></div></div></section>
<section class="section"><div class="container cta-panel"><div><p class="eyebrow">Have a project in mind?</p><h2>Let’s make something people remember.</h2></div><a class="button" href="contact.php">Tell us about it <span>→</span></a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
